### ISSUE TITLE
Support Hedgehog Skipping

### ISSUE THREAD

**Issue by gwils** [qfpl/tasty-hedgehog#61]
The next version of Hedgehog will have "skipping" (https://github.com/hedgehogqa/haskell-hedgehog/pull/454). It will also break `Internal` APIs that we depend on.

We should at least upgrade to build successfully with the new version, and it would be good to support the skipping functionality as well. @mbg Would you like to have a go at this? I could do the former option myself but don't have time for the latter.

**Comment by mbg** [comment]
I should have time this week to look into this.

**Comment by mbg** [comment]
I have spent a bit of time with this and my impression so far is that:

- Getting `tasty-hedgehog` to just compile with the new version of `hedgehog`, while not supporting the skipping functionality, isn't particularly nice. The main issue is in `reportOutput` where we currently rely on `failureSize` and `failureSeed`. I read through the [conversion touching on this](https://github.com/hedgehogqa/haskell-hedgehog/pull/454#discussion_r941278671) which notes that it is not really possible to obtain that information anymore. That means, we would need to change what we report in `reportOutput` to something else and then adjust `HedgehogReplay` accordingly, or just report a dummy value for `Size`.
- That basically takes us to supporting skipping functionality straight away and the [changes proposed by @ChickenProp](https://github.com/hedgehogqa/haskell-hedgehog/pull/454#discussion_r945670600). That compiles (+ some suitable changes to the `IsOption` instance for `HedgehogReplay`), but doesn't provide great UX due to the way the new skipping functionality expects tests to be organised vs how they are organised in `tasty`. 

Let's consider the changes for the latter. We replace `Size` with `Skip` in the definition of `HedgehogReplay` and update the `IsOption` instance to use `skipDecompress`:

```haskell
-- | The replay token to use for replaying a previous test run
newtype HedgehogReplay = HedgehogReplay (Maybe (Skip, Seed))
  deriving (Typeable)

instance IsOption HedgehogReplay where
  defaultValue = HedgehogReplay Nothing
  parseValue v = HedgehogReplay . Just <$> replay
    -- Reads a replay token in the form "{skip} {seed}"
    where replay = (,) <$> skipDecompress (unwords skip) <*> safeRead (unwords seed)
          (skip, seed) = splitAt 1 $ words v
  optionName = return "hedgehog-replay"
  optionHelp = return "Replay token to use for replaying a previous test run"
```

This works fine. We need to update `reportOutput` to produce corresponding replay instructions. This is more of a problem:

```haskell
reportOutput :: Bool
             -> UseColor
             -> PropertyName
             -> Report Result
             -> IO String
reportOutput showReplay useColor name report = do
  s <- renderResult useColor (Just name) report
  pure $ case reportStatus report of
    Failed fr ->
      let
        seed = reportSeed report
        replayStr =
          if showReplay
          then
            "\nUse '--hedgehog-replay \"" ++
            skipCompress (SkipToShrink 0 $ failureShrinkPath fr) ++ " " ++ show seed ++
            "\"' to reproduce."
          else ""
      in
        s ++ replayStr ++ "\n"
    _ -> s
```

Obtaining the `Seed` with `reportSeed` is fine, but we need to generate a `Skip` value. We have the right `ShrinkPath` (via `failureShrinkPath` from the `FailureReport`), but we don't have a good value for `TestCount`. Setting it to `0` makes it compile, but isn't particularly meaningful. `reportOutput` is called by `run` in the `IsTest` instance for `HP`, but as far as I can tell we do not have access to the `tasty` test number there (if there even is such a thing). 

The existing behaviour of `HedgehogReplay` with older versions of `hedgehog` is that every property is re-run with the provided `Size` and `Seed`. With the above change, the same happens, except with the same `Skip` value and `Seed`. This is not ideal though, because now the `ShrinkPath` for a specific property is applied to _all_ properties, which causes most of them to fail. The `Skip` should really only be applied to one specific test. 

I suppose we could include the `TestName` in the replay instructions / in `HedgehogReplay` and then check against that in `run`, skipping other properties. I would also then change having a `Skip` value to just the `ShrinkPath`. What do you think?

**Comment by gwils** [comment]
This sounds like a complex situation with no good answers. What you've described sounds reasonable to me. At this point, you're more up to date on Hedgehog internals than I am :)

**Comment by moodmosaic** [comment]
> The next version of Hedgehog will have "skipping" ([hedgehogqa/haskell-hedgehog#454](https://github.com/hedgehogqa/haskell-hedgehog/pull/454)).

Available now in [hedgehog 1.2](#463).

**Comment by ChickenProp** [comment]
Ah, I'm sorry this is awkward for you :(

> we don't have a good value for `TestCount`. Setting it to `0` makes it compile, but isn't particularly meaningful.

You should be able to use `reportTests report` for this.

One thing you could do here is to use `SkipToTest` instead of `SkipToShrink`. Shrink paths indeed are only valid for one test at a time. If you're re-running the whole suite, then `SkipToTest` gets closer to your current behavior. You might then want to consider some other way of exposing shrink paths, but in the meantime users can use `HEDGEHOG_SKIP` and `HEDGEHOG_SEED`.

I believe (based on my understanding of the current and past hedgehog behavior and your usage) this would have two differences.

1. Tests will run the specified test number, but then if that one passed, they'll continue to failure instead of stopping after just one. I guess this is awkward for you because it'll slow down replaying quite a lot. I think you could get around this by applying `withTests testNum` to the property. (`testNum + 1` or `testNum - 1` might be correct instead, but I *think* I implemented it such that `withSkip (SkipToTest n) . withTests n` would run test `n` and no others. I admittedly didn't really think about this at the time I was writing it.)
2. If two tests fail at the same test number, they'll now both fail when replayed. I think this wouldn't have been the case before, because they would have needed different seeds to reproduce.

**Comment by frasertweedale** [comment]
Note that hedgehog < 1.2 is not compatible with GHC 9.4.
Is it possible to cut a "make it work" release, and follow up with a proper solution later,
in order to un-break on GHC 9.4 projects that use *tasty-hedgehog*?

**Comment by moodmosaic** [comment]
> Note that hedgehog < 1.2 is not compatible with GHC 9.4.

Perhaps we can make a hedgehog 1.1.1 metadata revision on hackage, if that helps.

**Comment by frasertweedale** [comment]
> Perhaps we can make a hedgehog 1.1.1 metadata revision on hackage, if that helps.

I can't see how a metadata revision would help folks on GHC 9.4:

- `hedgehog < 1.2` does not build with GHC 9.4
- *tasty-hedgehog* does not build against `hedgehog-1.2`.

**Comment by moodmosaic** [comment]
Yeah, you are right, the metadata revision won't help because of https://gitlab.haskell.org/ghc/ghc/-/wikis/migration/9.4#-is-now-a-type-operator.

**Comment by mbg** [comment]
It seems like it might be possible to create a `1.1.2` release by branching off https://github.com/hedgehogqa/haskell-hedgehog/commit/bf04960348d0a32aab9dc8ff39c93b7743fa1153 and then cherry-picking some of the later commits, particularly https://github.com/hedgehogqa/haskell-hedgehog/commit/4a4d5634f8f5e1c2476796bb88cf22b2ba3c276e. In theory, the only change there would be the equivalent of metadata revisions + the addition of the `TypeOperators` extension, so a `1.1.2` tag seems OK. I have never released a lower version after a higher version is already out, though, so I don't know whether there might be any undesired consequences of doing this.

**Comment by moodmosaic** [comment]
Might be worth trying uploading a [package candidate](https://hackage.haskell.org/upload) to find out. A hypothetical 1.1.2 release would be basically 1.1.1 + ghc 9.4 support, right?

**Comment by frasertweedale** [comment]
There are no problems releasing new point releases on older major versions.  I've done it several times.  It is a mark of a mature project ;)

**Comment by moodmosaic** [comment]
New point release on previous major is now up: https://hackage.haskell.org/package/hedgehog-1.1.2.

**Comment by gwils** [comment]
I've tested and made a metadata revision to tasty-hedgehog-1.3.0.0 to allow hedgehog-1.1.2

**Comment by frasertweedale** [comment]
Thanks comrades!
